name: Wang Ruipeng's blog
title: CODE THE WORLD ANEW
description: This is Wang Ruipeng's personal website and portfolio.
tags:
  - blog

show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact

email:
  See: contact@wangruipeng.com
disqus_username:
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id:
